name: checkout

on: [push]

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - name: list of files
        run : |
          ls -a 
          pwd 
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{ github.token }}"
      - uses: actions/checkout@v1
      - name: list of files after
        run : |
          ls -a 
          pwd 
    