name: checkout

on: [push]

jobs: 
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: checkout before action 
        run: |
          ls -a 
          pwd 
      - name: checkout
        uses: actions/checkout@v2
          with:
            fetch-depth: 0
      - name: list of files
        run : |
          ls -a 
          pwd 
    